http {
  upstream oommah_servers {
      server server1.oommah.com;
      server server2.oommah.com;
      server server3.oommah.com;
  }

  server {
      listen 80;
      server_name oommah.com www.oommah.com;

      location / {
          proxy_pass http://oommah_servers;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }
}

